### ISSUE TITLE
SlickBot adds "NICE" to messages that do not contain 69

### ISSUE THREAD

**Issue by andrewd18** [UpsidePotential/SlickBot#51] opened 2020-08-21 21:27 UTC
SlickBot is adding "NICE" to messages it should not. For example:

![text_string_does_not_contain_69](https://user-images.githubusercontent.com/761994/90936380-b226af00-e3ca-11ea-889a-6f1edde2aabf.png)

I suspect this is related to the "@freedeau" part of the message which is, under the hood, a [Snowflake object](https://discord.js.org/#/docs/main/stable/typedef/Snowflake). My guess is that string is what SlickBot is reading, not the converted, clickable string visible to the user in the regular Discord client.

**Comment by UpsidePotential** [comment] 2020-08-23 17:36
should be monitored more...  if this is not annoying i might close it as a feature not a bug.

**Comment by andrewd18** [comment] 2020-08-25 15:26
It is doing it for @chulas as well as @freedeau.

**Closed** 2020-08-31 18:59 UTC
